export const COUNTRY_NAME_MAP = {
  AE: "Ả Rập Xê Út",
  AR: "Argentina",
  AT: "Áo",
  Australia: "Úc",
  BE: "Bỉ",
  BG: "Bulgaria",
  Brazil: "Brazil",
  BS: "Bahamas",
  Canada: "Canada",
  CH: "Thụy Sĩ",
  CL: "Chile",
  China: "Trung Quốc",
  CO: "Colombia",
  CZ: "Séc",
  Germany: "Đức",
  Denmark: "Đan Mạch",
  DO: "Dominica",
  Spain: "Tây Ban Nha",
  FI: "Phần Lan",
  France: "Pháp",
  "United Kingdom": "Anh",
  Greece: "Hy Lạp",
  HK: "Hồng Kông",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  India: "Ấn Độ",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  Italy: "Ý",
  JO: "Jordan",
  Japan: "Nhật Bản",
  KE: "Kenya",
  "South Korea": "Hàn Quốc",
  KY: "Cayman",
  KZ: "Kazakhstan",
  LT: "Litva",
  LU: "Luxembourg",
  MA: "Ma-rốc",
  MT: "Malta",
  Mexico: "Mexico",
  MY: "Malaysia",
  Netherlands: "Hà Lan",
  Norway: "Na Uy",
  NZ: "New Zealand",
  PL: "Ba Lan",
  PR: "Puerto Rico",
  QA: "Qatar",
  RO: "Romania",
  RS: "Serbia",
  Russia: "Nga",
  Sweden: "Thụy Điển",
  SG: "Singapore",
  SK: "Slovakia",
  TH: "Thái Lan",
  TN: "Tunisia",
  TR: "Thổ Nhĩ Kỳ",
  TW: "Đài Loan",
  "United States": "Mỹ",
  VE: "Venezuela",
  ZA: "Nam Phi",
};
